/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowIndexRouteImport } from './routes/flow/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardFlowsIndexRouteImport } from './routes/dashboard/flows/index'
import { Route as DashboardCredentialsIndexRouteImport } from './routes/dashboard/credentials/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowIndexRoute = FlowIndexRouteImport.update({
  id: '/flow/',
  path: '/flow/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFlowsIndexRoute = DashboardFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCredentialsIndexRoute =
  DashboardCredentialsIndexRouteImport.update({
    id: '/credentials/',
    path: '/credentials/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/flow/': typeof FlowIndexRoute
  '/dashboard/credentials/': typeof DashboardCredentialsIndexRoute
  '/dashboard/flows/': typeof DashboardFlowsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/flow': typeof FlowIndexRoute
  '/dashboard/credentials': typeof DashboardCredentialsIndexRoute
  '/dashboard/flows': typeof DashboardFlowsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/flow/': typeof FlowIndexRoute
  '/dashboard/credentials/': typeof DashboardCredentialsIndexRoute
  '/dashboard/flows/': typeof DashboardFlowsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/flow/'
    | '/dashboard/credentials/'
    | '/dashboard/flows/'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/flow'
    | '/dashboard/credentials'
    | '/dashboard/flows'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/flow/'
    | '/dashboard/credentials/'
    | '/dashboard/flows/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  FlowIndexRoute: typeof FlowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/': {
      id: '/flow/'
      path: '/flow'
      fullPath: '/flow/'
      preLoaderRoute: typeof FlowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/flows/': {
      id: '/dashboard/flows/'
      path: '/flows'
      fullPath: '/dashboard/flows/'
      preLoaderRoute: typeof DashboardFlowsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/credentials/': {
      id: '/dashboard/credentials/'
      path: '/credentials'
      fullPath: '/dashboard/credentials/'
      preLoaderRoute: typeof DashboardCredentialsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCredentialsIndexRoute: typeof DashboardCredentialsIndexRoute
  DashboardFlowsIndexRoute: typeof DashboardFlowsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCredentialsIndexRoute: DashboardCredentialsIndexRoute,
  DashboardFlowsIndexRoute: DashboardFlowsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  FlowIndexRoute: FlowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
